// HAL Garage Club: simplifica administración y permite asignar premios/productos a categorías.
(() => {
  const path=location.pathname;
  const isAdmin=/\/club-hal-garage\/admin\.html$/.test(path);
  const isModules=/\/club-hal-garage\/admin-modulos\.html$/.test(path);
  const SB_URL='https://maqnglazkhwtzskfddgc.supabase.co';
  const SB_KEY='sb_publishable_gIB6HrGHT3X7CwIjAHGO8Q_7hYro-I_';
  const client=(window.supabase&&window.supabase.createClient)?window.supabase.createClient(SB_URL,SB_KEY,{auth:{autoRefreshToken:true,persistSession:false,detectSessionInUrl:false}}):null;
  function removeCategoryModule(){document.querySelectorAll('#modules .card,#tabs .tab').forEach(el=>{if((el.textContent||'').includes('Categorías'))el.remove()});document.querySelectorAll('#content a').forEach(a=>{if((a.textContent||'').toLowerCase().includes('editar categorías'))a.closest('.card')?.remove()});if(isModules&&new URLSearchParams(location.search).get('module')==='categories')location.replace('./admin-modulos.html?module=rewards')}
  function categorySelect(id,label){return `<div><label>${label}</label><select id="${id}"><option value="">Todas las categorías</option><option value="BRONCE">BRONCE</option><option value="PLATA">PLATA</option><option value="ORO">ORO</option><option value="VIP">VIP</option></select></div>`}
  function addRewardControls(){if(!isModules||new URLSearchParams(location.search).get('module')!=='rewards')return;const title=[...document.querySelectorAll('#content h3')].find(x=>x.textContent.includes('Premio del Club'));if(title&&!document.getElementById('rcat')){const grid=title.closest('.card')?.querySelector('.grid2');if(grid)grid.insertAdjacentHTML('beforeend',categorySelect('rcat','Categoría que puede canjearlo'))}const pt=[...document.querySelectorAll('#content h3')].find(x=>x.textContent.includes('Producto del catálogo'));if(pt&&!document.getElementById('pcat')){const grid=pt.closest('.card')?.querySelector('.grid2');if(grid)grid.insertAdjacentHTML('beforeend',categorySelect('pcat','Categoría que puede canjearlo'))}}
  function patchRewardSave(){if(!isModules||new URLSearchParams(location.search).get('module')!=='rewards'||!client||window.__halRewardPatched)return;if(typeof window.saveReward!=='function'||typeof window.saveProduct!=='function')return;window.__halRewardPatched=true;window.saveReward=async function(){const id=document.getElementById('rid')?.value;const p={title:document.getElementById('rtitle')?.value.trim(),description:document.getElementById('rdesc')?.value.trim(),reward_type:document.getElementById('rtype')?.value,stock:document.getElementById('rstock')?.value===''?null:Number(document.getElementById('rstock')?.value),starts_at:document.getElementById('rstart')?.value||null,expires_at:document.getElementById('rexp')?.value||null,active:!!document.getElementById('ractive')?.checked,category:document.getElementById('rcat')?.value||null};if(!p.title)return window.msg?.('Ingresa un título.',true);const r=id?await client.from('club_rewards').update(p).eq('id',id):await client.from('club_rewards').insert(p);if(r.error)return window.msg?.(r.error.message,true);location.reload()};window.saveProduct=async function(){const id=document.getElementById('pid')?.value;const p={name:document.getElementById('pname')?.value.trim(),description:document.getElementById('pdesc')?.value.trim(),points_cost:Math.max(0,Number(document.getElementById('pcost')?.value||0)),stock:document.getElementById('pstock')?.value===''?null:Number(document.getElementById('pstock')?.value),image_path:document.getElementById('pimage')?.value.trim()||null,active:!!document.getElementById('pactive')?.checked,category:document.getElementById('pcat')?.value||null,updated_at:new Date().toISOString()};if(!p.name)return window.msg?.('Ingresa un nombre.',true);const r=id?await client.from('club_catalog_products').update(p).eq('id',id):await client.from('club_catalog_products').insert(p);if(r.error)return window.msg?.(r.error.message,true);location.reload()};const oldER=window.editReward,const oldEP=window.editProduct;window.editReward=async function(id){await oldER?.(id);if(client){const r=await client.from('club_rewards').select('category').eq('id',id).maybeSingle();if(!r.error&&document.getElementById('rcat'))document.getElementById('rcat').value=r.data?.category||''}};window.editProduct=async function(id){await oldEP?.(id);if(client){const r=await client.from('club_catalog_products').select('category').eq('id',id).maybeSingle();if(!r.error&&document.getElementById('pcat'))document.getElementById('pcat').value=r.data?.category||''}}}
  function patchCards(){if(!isModules||new URLSearchParams(location.search).get('module')!=='rewards'||!client)return;document.querySelectorAll('#content .item').forEach(async item=>{if(item.dataset.halCategoryDone)return;const btn=item.querySelector('button[onclick*="editReward"],button[onclick*="editProduct"]');const onclick=btn?.getAttribute('onclick')||'';const m=onclick.match(/'(.*?)'/);if(!m)return;const id=m[1];const isR=onclick.includes('editReward');const table=isR?'club_rewards':'club_catalog_products';const r=await client.from(table).select('category').eq('id',id).maybeSingle();if(r.error)return;const meta=item.querySelector('.meta');if(meta){const c=r.data?.category||'Todas';meta.innerHTML+=`<br>👑 Categoría: <b>${c}</b>`}item.dataset.halCategoryDone='1'})}
  const observer=new MutationObserver(()=>{removeCategoryModule();addRewardControls();patchRewardSave();patchCards()});observer.observe(document.documentElement,{subtree:true,childList:true});removeCategoryModule();addRewardControls();patchRewardSave();
})();
